name: 'InstaWP WordPress Github Action'
description: 'WordPress Testing Simplied with InstaWP Templates'
author: 'InstaWP'
branding:
  icon: 'zap'  
  color: 'green'

inputs:
  GITHUB_TOKEN:
    description: 'GitHub token'
    required: true
  INSTAWP_TOKEN:
    description: 'InstaWP API Token (site:create)'
    required: true
  INSTAWP_TEMPLATE_SLUG:
    description: 'InstaWP Template Slug'
    required: true
  REPO_ID:
    description: 'InstaWP Repo ID'
    required: true

runs:
  using: 'node12'
  main: 'dist/index.js'